'use strict';
const D=window.LAB, $=id=>document.getElementById(id), pct=x=>x===null?'N/A':(x*100).toFixed(2)+'%', num=x=>x===null?'N/A':x.toLocaleString('en-US',{maximumFractionDigits:4});
const names={baseline_net:'Volatility-controlled · net 5 bps',baseline_gross:'Volatility-controlled · gross',equal_net:'Equal thirds · monthly · net',trend_net:'Trend only · monthly · net',cash:'Cash · assumed 2%',lookback_126:'Sensitivity · trend 126 sessions',vol_window_126:'Sensitivity · covariance 126 sessions',reference_6pct:'Sensitivity · reference 6%',reference_14pct:'Sensitivity · reference 14%',cost_10bps:'Sensitivity · costs 10 bps',cost_20bps:'Sensitivity · costs 20 bps',equal_gross:'Equal thirds · gross',trend_gross:'Trend only · gross'};
$('status').textContent=`Valuation through ${D.as_of} · ${D.methodology}`;
$('method-version').textContent=`${D.methodology} · 252-session trend · 63-session covariance · 10% volatility reference · 5 bps transaction costs`;
function table(headers,rows){return '<div class="table-wrap"><table><thead><tr>'+headers.map(h=>`<th>${h}</th>`).join('')+'</tr></thead><tbody>'+rows.map(r=>'<tr>'+r.map(c=>`<td>${c}</td>`).join('')+'</tr>').join('')+'</tbody></table></div>';}
function plot(id,series,percent=false){const svg=$(id),H=+svg.getAttribute('viewBox').split(' ')[3],W=1000,p=48;const all=series.flatMap(s=>s.values.filter(v=>v!==null));let lo=Math.min(0,...all),hi=Math.max(...all)*1.08;if(hi===lo)hi=lo+1;let s='';for(let j=0;j<5;j++){let y=p+j*(H-2*p)/4,v=hi-j*(hi-lo)/4;s+=`<line x1="${p}" y1="${y}" x2="${W-p}" y2="${y}" stroke="#dce0d6"/><text x="0" y="${y+4}">${percent?pct(v):num(v)}</text>`;}series.forEach(line=>{let path='',gap=true;line.values.forEach((v,i)=>{if(v===null){gap=true;return;}path+=(gap?'M':'L')+(p+i*(W-2*p)/(line.values.length-1)).toFixed(2)+','+(H-p-(v-lo)/(hi-lo)*(H-2*p)).toFixed(2)+' ';gap=false;});s+=`<path d="${path}" fill="none" stroke="${line.color}" stroke-width="1.8"/>`;});s+=`<text x="${p}" y="${H-10}">${D.baseline[0].date}</text><text x="${W-p}" y="${H-10}" text-anchor="end">${D.as_of}</text>`;svg.innerHTML=s;}
Object.keys(D.summary).forEach(n=>$('scenario').add(new Option(names[n],n)));$('scenario').value='baseline_net';
function update(){let n=$('scenario').value,p=$('period').value,m=D.summary[n].metrics[p],c=D.summary[n].config;$('configuration').textContent=`${D.methodology} · ${c.strategy} · trend ${c.lookback} · covariance ${c.vol_window} · reference ${pct(c.vol_reference)} · costs ${c.cost_bps} bps · ${m.start}–${m.end}`;$('kpis').innerHTML=[['Annualized return',pct(m.annual_return)],['Annualized volatility',pct(m.annual_vol)],['Maximum drawdown',pct(m.max_drawdown)],['Excess-return Sharpe',num(m.sharpe)]].map(([a,b])=>`<article><small>${a}</small><strong>${b}</strong></article>`).join('');plot('paths',[{values:D.paths.baseline_gross.map(r=>r.index),color:'#b6c4bd'},{values:D.paths.baseline_net.map(r=>r.index),color:'#07796e'},{values:D.paths[n].map(r=>r.index),color:'#b56624'}]);$('comparison').textContent=`Period totals: turnover ${num(m.turnover_total)}×; transaction costs ${num(m.cost_index_points)} index points; average risky exposure ${pct(m.mean_risky_exposure)}.`;$('scenario-table').innerHTML=table(['Scenario','Return','Volatility','Sharpe','Drawdown'],Object.entries(D.summary).map(([k,v])=>{let t=v.metrics[p];return [names[k],pct(t.annual_return),pct(t.annual_vol),num(t.sharpe),pct(t.max_drawdown)];}));}
$('scenario').onchange=update;$('period').onchange=update;update();
plot('riskchart',[{values:D.risk.map(r=>r.forecast_target_vol),color:'#07796e'},{values:D.risk.map(r=>r.subsequent_realized_vol),color:'#b56624'}],true);plot('exposure',[{values:D.baseline.map(r=>1-r.cash_weight),color:'#07796e'}],true);
$('shocks').innerHTML=table(['Shock','Portfolio return','P&L / $1m'],Object.entries(D.shocks.shocks).map(([k,v])=>[k,pct(v.return),'$'+num(v.pnl_usd)]));$('notionals').innerHTML=table(['Sleeve','USD notional'],['US equity','Treasuries','Gold','Cash'].map((a,i)=>[a,'$'+num(i<3?D.shocks.risky_notionals_usd[i]:D.shocks.cash_usd)]));
D.baseline.forEach((r,i)=>$('audit-date').add(new Option(r.date,i)));$('audit-date').value='0';
function audit(){let r=D.baseline[+$('audit-date').value],i=r.instruction;$('audit-result').innerHTML=`<div class="columns"><article><h3>Signal and allocation</h3><p>Decision ${i?i.decision_date:'none'} → execution ${r.date}. Base forecast volatility ${i?pct(i.sigma_base):'N/A'}; scale ${i?num(i.scale):'N/A'}.</p>${table(['Sleeve','Signal','Target','Actual weight'],['Equity','Treasuries','Gold'].map((a,j)=>[a,i?i.signals[j]:'—',i?pct(i.target[['equity','treasury','gold'][j]]):'—',pct(r.weights[j])]))}</article><article><h3>Index reconciliation</h3>${table(['Component','Value'],[['Previous index',num(r.previous_wealth)],['Asset P&L',num(r.asset_pnl.reduce((a,b)=>a+b,0))],['Cash interest',num(r.cash_interest)],['Trading cost',num(-r.cost)],['Resulting index',num(r.index)],['Reconciliation residual',r.reconciliation_error.toExponential(2)],['Post-trade cash',num(r.cash)]])}</article></div>`;$('audit-json').textContent=JSON.stringify(r,null,2);$('snapshot-note').textContent=`Price snapshot SHA-256: ${D.snapshot.prices}. Full metadata accompanies the downloaded results.`;}
$('audit-date').onchange=audit;audit();let rev=D.revision;$('revision').textContent=`Observation ${rev.corrected_observation}: ${rev.change}. Original and revised calculations are retained separately. Affected records ${rev.first_affected}–${rev.last_affected}; maximum absolute index difference ${num(rev.max_absolute_index_difference)}. The results download includes dated differences and both result identifiers.`;
D.options.forEach((o,i)=>$('option-case').add(new Option(`${o.inputs.kind} · volatility ${pct(o.inputs.volatility)} · 100 units`,i)));
function option(){let o=D.options[+$('option-case').value];$('option-result').innerHTML=`<p>Spot = strike = ${num(o.inputs.spot)}; maturity 1 year; constant continuously compounded rate 3%; assumed volatility ${pct(o.inputs.volatility)}.</p>${table(['Price $','Delta $/point','Gamma $/point²','Vega $/1 vol point'],[[num(o.result.price),num(o.result.delta),num(o.result.gamma),num(o.result.vega_per_1pct)]])}${table(['Component','Delta exposure $','Offset hedge $'],['Equity','Treasuries','Gold'].map((n,j)=>[n,num(o.mapping.replication_risky_dollars[j]),num(o.mapping.offset_hedge_risky_dollars[j])]))}`;}$('option-case').onchange=option;option();
